global using AuthTest.Domain.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using System.Reflection;
global using AuthTest.Domain.Dtos.Account;
global using Dapper;
global using NLog;
global using System.Data;
global using AuthTest.Domain.Utility;
